# Generated by Django 6.0.5 on 2026-06-18 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blog_is_public"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="is_public",
            new_name="is_published",
        ),
    ]
