# Generated by Django 6.0.5 on 2026-06-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_rename_is_public_blog_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["title"],
                "verbose_name": "блог",
                "verbose_name_plural": "блоги",
            },
        ),
    ]
