# Generated by Django 6.0.5 on 2026-07-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_product_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_publish",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Статус публикации"
            ),
        ),
    ]
